name: CI
on:
  workflow_dispatch:
    inputs:
      runTrivy:
        description: Run Trivy scan
        type: boolean
        default: true
        required: false
  push:
    paths-ignore: ["**.md", "LICENSE", ".github/dependabot.yml"]
    branches: ["master", "main"]
  pull_request:
    paths-ignore: ["**.md", "LICENSE", ".github/dependabot.yml"]
    branches: ["master", "main"]
    types: [opened, reopened]

permissions: {}

defaults:
  run:
    shell: bash

concurrency:
  group: CI
  cancel-in-progress: false

jobs:
  scan:
    name: Trivy Scan
    runs-on: ubuntu-latest
    timeout-minutes: 5
    if: |
      inputs.runTrivy == true ||
      github.event_name == 'push'
    permissions:
      contents: read
      issues: write
      pull-requests: write
      security-events: write
      actions: read
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@v2
        with:
          disable-sudo: true
          egress-policy: audit

      - name: Checkout
        uses: actions/checkout@v7

      - name: Run Trivy
        uses: aquasecurity/trivy-action@v0.36.0
        with:
          scan-type: fs
          scanners: vuln,secret,misconfig
          scan-ref: ./
          format: sarif
          output: results.sarif
          severity: HIGH,CRITICAL
          exit-code: 1
        continue-on-error: true

      - name: Upload to code-scanning
        uses: github/codeql-action/upload-sarif@v4.38.0
        with:
          sarif_file: results.sarif

  tflint:
    name: TFLint
    runs-on: ubuntu-latest
    timeout-minutes: 5
    if: github.event_name == 'push'
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@v2
        with:
          disable-sudo: true
          egress-policy: audit

      - name: Checkout
        uses: actions/checkout@v7

      - name: Cache plugin dir
        uses: actions/cache@v6
        with:
          path: ~/.tflint.d/plugins
          key: ${{ matrix.os }}-tflint-${{ hashFiles('.tflint.hcl') }}

      - name: Setup TFLint
        uses: terraform-linters/setup-tflint@v6
        with:
          tflint_version: v0.52.0

      - name: Show version
        run: tflint --version

      - name: Init TFLint
        run: tflint --init
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - name: Run TFLint
        run: tflint -f compact

  release:
    name: Publish Release
    runs-on: ubuntu-latest
    timeout-minutes: 5
    needs: [scan]
    if: github.event_name == 'push'
    permissions:
      contents: write
      issues: write
      pull-requests: write
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@v2
        with:
          disable-sudo: true
          egress-policy: audit

      - name: Checkout
        uses: actions/checkout@v7
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v6
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          semantic_version: 25
          extra_plugins: |
            conventional-changelog-conventionalcommits@9.3.0
            @semantic-release/github@12.0.6
